# {{@@ header() @@}}

# Path to oh-my-zsh installation.
export ZSH="/home/$USER/.oh-my-zsh"

ZSH_THEME="agnoster"

plugins=(
  git
)

export EDITOR='nvim'
export PAGER='less'


# Color for man
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'


REPO_LOCATION="$HOME/Desktop"

{%@@ if profile == "Krapaince-arch" @@%}
export SOUNDBOARD_LOCATION=~/Music/Soundboard/
{%@@ endif @@%}

# Path
{%@@ if profile == "Krapaince-MASTER-arch" or profile == "Krapaince-arch" @@%}
export ANDROID_SDK=/opt/Android/platform-tools
export DOTNET_PATH=~/.dotnet/tools
LOCAL_BIN=~/.local/bin

PATH=$PATH:$DOTNET_PATH:$LOCAL_BIN:$ANDROID_SDK
{%@@ endif @@%}

CUSTOM_SCRIPT=$REPO_LOCATION/GIT/scripts

PATH=$PATH:$CUSTOM_SCRIPT

# Alias
source ~/.zsh_alias

# Include part
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH/oh-my-zsh.sh


{%@@ if profile == "Krapaince-MASTER-arch" or profile == "Krapaince-arch" @@%}
# zsh parameter completion for the dotnet CLI
_dotnet_zsh_complete()
{
  local completions=("$(dotnet complete "$words")")

  reply=( "${(ps:\n:)completions}" )
}
compctl -K _dotnet_zsh_complete dotnet
{%@@ endif @@%}
